includes:
  - '**/serviceblend.yaml'

services:
  serviceA:
    default: local
    environments:
      # docker compose
      local:
        endpoint: http://localhost:8080
        open: false
        apparatus: docker-compose
        envs: {}
        definition:
          version: '3'
          services:
            nginx:
              image: nginx:latest
              ports:
                - 8080:80

      one:
        endpoint: http://example.com
        open: true
        apparatus: sh
        definition: |
          echo hello world && tail -f /dev/null

      # docker compose
      staging:
        endpoint: http://localhost:8080
        open: false
        apparatus: docker-compose
        envs: {}
        definition:
          compose: ./docker-compose.yaml
          service: nginx2

  #     # endpoint
  #     production:
  #       plugin: endpoint
  #       definition: http://example.com

  serviceB:
    # default: local
    environments:
      staging:
        endpoint: http://localhost:8080
        open: false
        apparatus: docker-compose
        envs: {}
        definition:
          compose: ./docker-compose.yaml
          service: nginx

      # local:
      #   endpoint: http://localhost:8080
      #   open: true
      #   apparatus: docker-compose
      #   envs: {}
      #   definition:
      #     version: '3'
      #     services:
      #       nginx:
      #         image: nginx:latest
      #         ports:
      #           - 8080:80

      # proxy
      # local:
      #   endpoint: http://localhost:8080
      #   plugin: proxy
      #   definition:
      #     service: http://example.com
      #     proxy: http://localhost:8080

  #     # command
  #     staging:
  #       env: {}
  #       plugin: command
  #       definition: 'python -m http.serve'

  #     # http proxy
  #     production: 'https://example.com'

  #   dependsOn:
  #     - serviceB
